[package]
name = "spaces_to_underscores"
version = "0.1.0"
authors = ["HTunne <htunnicliffe@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
